import type { Metadata } from "next";
import { Crimson_Text } from "next/font/google";
import "./globals.css";
import { Analytics } from "@vercel/analytics/next";

const crimsonText = Crimson_Text({
  weight: ["400", "600"],
  subsets: ["latin"],
  fallback: [
    "Georgia",
    "Garamond",
    "Palatino",
    "Book Antiqua",
    "Times New Roman",
    "serif",
  ],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${crimsonText.className} antialiased bg-white text-black`}
        suppressHydrationWarning
      >
        {children}
        <Analytics />
      </body>
    </html>
  );
}
